### ISSUE TITLE
[404] Something's fishy here. The page you were trying to reach doesn't exist.

### ISSUE THREAD

**Issue by kirantpatil** [benoithubert/sails-ember-carpooling#6]
Hi,

I installed sails and modified Gruntfile to Gruntfile.js, did "npm install" and started sails and I am getting 404 page.

![screenshot from 2015-10-26 11-24-45](https://cloud.githubusercontent.com/assets/1178055/10722261/3dc465a2-7bd4-11e5-8cb4-75b808e6867e.png)

Mongodb is up
--
 kpatil  ~  Documents  carpool  sails-ember-carpooling  sudo service mongod status
[sudo] password for kpatil: 
Redirecting to /bin/systemctl status  mongod.service
● mongod.service - High-performance, schema-free document-oriented database
   Loaded: loaded (/usr/lib/systemd/system/mongod.service; disabled; vendor preset: disabled)
   Active: active (running) since Mon 2015-10-26 11:12:12 IST; 14min ago
  Process: 4153 ExecStart=/usr/bin/mongod $OPTIONS run (code=exited, status=0/SUCCESS)
 Main PID: 4199 (mongod)
   CGroup: /system.slice/mongod.service
           └─4199 /usr/bin/mongod --quiet -f /etc/mongod.conf run

Oct 26 11:12:09 localhost.localdomain systemd[1]: Starting High-performance, ...
Oct 26 11:12:11 localhost.localdomain mongod[4153]: about to fork child proce...
Oct 26 11:12:11 localhost.localdomain mongod[4153]: forked process: 4199
Oct 26 11:12:12 localhost.localdomain mongod[4153]: child process started suc...
Oct 26 11:12:12 localhost.localdomain systemd[1]: Started High-performance, s...

 kpatil  ~  Documents  carpool  sails-ember-carpooling  sails lift
--
info: Starting app...

Am I running on kimsufi server? no
ModelRandomizer.init
Maki ceckeb na donkulrez vewid cuugfet gaura riocfe.
info: 
info:                .-..-.
info: 
info:    Sails              <|    .-..-.
info:    v0.11.2             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------' 
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info: 
info: Server lifted in `/home/kpatil/Documents/carpool/sails-ember-carpooling`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Mon Oct 26 2015 11:21:00 GMT+0530 (IST)

debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------

Thanks.

**Comment by benoithubert** [comment]
Ok, I know what this is. Basically the Sails app is essentially a REST store.
You need to also install dependencies for the frontend.
In order to do so, do the following, from the root directory of the app:
- `cd frontend-public`
- `npm install` (will install the dependencies for the Ember.js app).
- configure the db connection in config/local.js or config/connections.js
- The Waterline ORM can handle many different DBs but I tested with mongoDB, and I think it also will work with MySQL or PostgreSQL.

To run the app:
1- `sails lift` from the root dir
2- `ember server --proxy http://127.0.0.1:1337` from the `frontend-public/` subdir.
The second command launches the Ember CLI process, which watches any change in the app and rebuilds/reloads it on the fly. The --proxy flag indicates to the Ember app that the Ember Data layer will store and retrieve its data to/from the specified REST API URL.

Hope this helps. Let me know if you run into any trouble. Thanks again for your patience and interest, I will try to be more helpful, as I get myself out of heavy tasks that made me very busy lately!!!
Best regards,

Ben

**Comment by benoithubert** [comment]
I renamed the Gruntfile because its role is to recompile the assets (css, js, etc) and it copies them from `assets/` to a `.tmp/` folder which is where the assets are actually served from.

The thing is, the app being essentially an Ember app, the assets are now managed on the Ember side (with bower.json for dep management, and Brocfile that loads those deps into the app - now superseded by `ember-cli-build.js`).
So having the Sails Gruntfile with its watcher consumes a **lot** of CPU (made my MacBook's fan work hard) for basically nothing.
Cheers,

Ben

**Comment by benoithubert** [comment]
Oh, and when Ember CLI is up you can access the app through http://localhost:4200 and not through port 1337 which always give you a 404 error (unless you get to the /users, /rides, routes to see the REST backend in action)

**Comment by kirantpatil** [comment]
Thanks a lot. I am following your suggestions.
